# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(450, 800)
        MainWindow.setMinimumSize(QtCore.QSize(450, 800))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.text_widget = QtWidgets.QWidget(parent=self.widget)
        self.text_widget.setObjectName("text_widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.text_widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.edt_text = QtWidgets.QTextEdit(parent=self.text_widget)
        self.edt_text.setObjectName("edt_text")
        self.horizontalLayout.addWidget(self.edt_text)
        self.verticalLayout_2.addWidget(self.text_widget)
        self.btn_widget = QtWidgets.QWidget(parent=self.widget)
        self.btn_widget.setMinimumSize(QtCore.QSize(0, 90))
        self.btn_widget.setMaximumSize(QtCore.QSize(16777215, 90))
        self.btn_widget.setObjectName("btn_widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.btn_widget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.save_btn = QtWidgets.QPushButton(parent=self.btn_widget)
        self.save_btn.setMinimumSize(QtCore.QSize(120, 50))
        self.save_btn.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setFamily("Monaco")
        font.setPointSize(15)
        self.save_btn.setFont(font)
        self.save_btn.setStyleSheet("QPushButton {\n"
"    border:none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border-radius:6px;\n"
"    border:7px;\n"
"    \n"
"    border-color: rgb(64, 58, 232);\n"
"    \n"
"    background-color: rgb(85, 81, 181);\n"
"}")
        self.save_btn.setObjectName("save_btn")
        self.horizontalLayout_2.addWidget(self.save_btn)
        self.ext_btn = QtWidgets.QPushButton(parent=self.btn_widget)
        self.ext_btn.setMinimumSize(QtCore.QSize(120, 50))
        self.ext_btn.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setFamily("Monaco")
        font.setPointSize(15)
        self.ext_btn.setFont(font)
        self.ext_btn.setStyleSheet("QPushButton {\n"
"    border:none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border-radius:6px;\n"
"    border:7px;\n"
"    \n"
"    background-color: rgb(204, 57, 72);\n"
"    border-color: rgb(255, 20, 45);\n"
"\n"
"}")
        self.ext_btn.setObjectName("ext_btn")
        self.horizontalLayout_2.addWidget(self.ext_btn)
        self.verticalLayout_2.addWidget(self.btn_widget)
        self.verticalLayout.addWidget(self.widget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Student Note (beta)"))
        self.save_btn.setText(_translate("MainWindow", "Save File"))
        self.ext_btn.setText(_translate("MainWindow", "Exit"))
